@baseUrl=http://localhost:8000/api/workspaces


### Create new workspace
POST {{baseUrl}}
Content-Type: application/json

{
    "name": "Open Source Contributors",
    "description": "Community-driven open source project collaboration",
    "icon": "🌍",
    "settings": {
        "theme": "light",
        "notifyOwnerOnMemberJoin": false,
        "visibility": "public",
        "maxMembers": 40
    }
}


### Update workspace 
PATCH  {{baseUrl}}/696f50662845c5435314806e
Content-Type: application/json

{
    
    "icon": "⚡",
    "settings": {
        "theme": "light",
        "notifyOwnerOnMemberJoin": true,
        "visibility": "private",
        "maxMembers": 80
    }
}

### Get workspace details
GET {{baseUrl}}/696f50662845c5435314806e

### Get all workspaces
GET {{baseUrl}}


### Delete workspace
DELETE {{baseUrl}}/696f50662845c5435314806e